### ISSUE TITLE
Starting from scratch...?

### ISSUE THREAD

**Issue by astoff** [jdtsmith/python-mls#13]
Hi JD, I was thinking about the problems this package solves and the ones it doesn't, and perhaps starting afresh might be a good idea. More specifically, I've sketched a little communication protocol which is not as complex as Jupyter or network-minded like nREPL. I think it's possible to create a framework where defining a fully-featured REPL (completion, multiline editing, etc) needs just a little bit of "backend" code in the target language plus a tiny bit of Elisp. Have a look [here](https://github.com/astoff/drepl) if you are interested and let me know what you think :-).

**Comment by jdtsmith** [comment]
Hey funny, was just thinking about reaching out to you.  I think I mentioned it a while back, but `python-mls` is actually a small piece in a much larger puzzle — an iPython shell package which fully replaces `python-inferior-shell`. As yet unreleased, but I'm calling `iPy`.  `python-mls` just handles the multiline catch & edit and prompt recognition, with some useful callback hooks for prompt changes, etc.  I put it out there _ala carte_ to iron out the kinks, but also because it works just as well with normal Python shells.

In any case, I've been using iPy for a couple years, and in the past year began the process of converting it to a core/extensions setup, which is where it got stranded (the core still works great, just finalizing the extension details).   All of iPy's communication happens _over the wire_ (no ZeroMQ libraries or anything else), using a custom process function which sits on top of comint's filter function.  It's been quite a process getting something smooth, interruptible, robust, and which yields a "normal seeming" iPython interactive experience, but it's been pretty well-behaved for months now.  It has a command queue system with "hidden" command capability built-in.  It works great for completion, eldoc documentation, source visiting, etc.  I've even got a transient-based iPy Shell Manager in core for starting/configuring/associating shells to buffers, so you can have an arbitrary combination of buffers and shells, either one remote or local.  (Planned) extensions are many and varied: I have imgcat based inline images (or in a dedicated buffer), traceback scanning/navigation/code eval, a debug interface to iPDB inspired by IDLWAVE's, and several others in mind.  I'd also like to do something sensible with tree-sitter (have you played with the new `comint-indirect-buffer`?).

First on your DREPL code: lots of cool ideas!  I didn't even know about `ansi-osc-handlers`.  I actually implemented something like that myself in the tight outer process function (imgcat uses this).  Mime type display?  I have (imgcat PNG) images, but are you doing (in principle) LaTeX fragments too?   What about HTML (like pandas tables)?

I'm hoping to clean it up and get a release out "soon", but the surface area of potential problems in the cross section between iPython (with all its versions and variations) and a tight interruptible Emacs async process interface is... daunting.    I sort of expect it to fall on its face for the first few other users.  In any case, I was hoping I might be able to bounce some of this stuff off you, and in an ideal world get you to do some high-level testing and problem-solving with me.  I suspect some of the features you're imagining in a DREPL-iPython could fit well as extensions.  Sorry for the brain dump; closing this to keep semi-private.  Feel free to email or perhaps we could chat sometime.
