### ISSUE TITLE
 Symbol’s function definition is void: py-execute-buffer

### ISSUE THREAD

**Issue by artpelling** [jdtsmith/python-mls#2]
Hello, great package thank you :)

I have configured python with `lsp` with `mspyls`. After installing the package with `use-package` as suggested, the function `py-execute-buffer` becomes unknown. If I manually start a python process with `M-x run-python` and then send the buffer everything works fine.

Any ideas?

**Comment by jdtsmith** [comment]
The LSP setup shouldn't have an impact.  

Confusingly, there are two popular packages which provide a `python-mode`.  I believe `py-execute-buffer` is from the (non-builtin) [`python-mode`](https://melpa.org/#/python-mode) available on MELPA.   Maybe you have that installed? Whereas `python.el` (_also_ providing `python-mode`) is bundled with Emacs.  

Can you determine which mode you are in in your Python buffer?  E.g. `C-h m` for me says:

```
Python mode defined in ‘python.el’:
Major mode for editing Python files.
```

I use `C-c C-p` to start a shell, and `C-c C-c` to send the buffer.  

For your particular issue, it shouldn't matter what mode is operating in a python source buffer (except for one small thing: python-MLS patches python.el's buffers to avoid copying the "..." decoration in).  

I'd guess your issue has something to do with the way your are loading your (non-builtin) python-mode.  Since `python-MLS` does `(require 'python)`, if it's loaded first, I bet your MELPA package isn't being setup to activate upon opening .py files.  If so, reversing the order of loading should work.  Or (simpler) just remove the other version and switch to using the built-in mode.

**Comment by artpelling** [comment]
Thanks for the swift reply, I am indeed using python-mode from MELPA.

`C-h m` gives me
```
Python mode defined in ‘python-mode.el’:
Major mode for editing Python files.
```
which is intended.

Upon further investigation I found out that `mspyls` is deprecated and I have switched to `pyright`.
`py-execute-buffer` is no longer unknown and works as intended again.

It might be noteworthy that I did not change the order of loading the packages, `python-mls` was loaded last in both cases.

However, `python-mls` now does not work inside the python buffer...

I will try to investigate further tomorrow

**Comment by jdtsmith** [comment]
I can't see how the LSP server would affect this.  You mean it does not work at all in the inferior python shell buffer?  Does MELPA python-mode supply such a shell itself?  python-MLS "turns itself on" with `(add-hook 'inferior-python-mode-hook #'python-mls-mode)`.   So if MELPA's python mode has its own associated shell mode, this would't work.  You could try M-x python-mls-mode to see.

**Comment by artpelling** [comment]
OK, it is a misunderstanding then. I thought that it should work for both python-modes.
When I envoke `M-x python-mls-mode` inside a MELPA Python shell I get

```
funcall-interactively: Wrong type argument: symbolp, ("\\_<\\(?:\\(?:a\\(?:nd\\|s\\(?:sert\\|ync \\(?:for\\|with\\)\\)?\\|wait\\)\\|break\\|continue\\|del\\|e\\(?:l\\(?:if\\|se\\)\\|x\\(?:cept\\|ec\\)\\)\\|f\\(?:inally\\|or\\)\\|global\\|i[fns]\\|lambda\\|not\\|or\\|pass\\|r\\(?:aise\\|eturn\\)\\|w\\(?:hile\\|ith\\)\\|yield\\)\\)\\_>" ("\\_<\\(?:async def\\|class\\|def\\)\\_>" . py-def-class-face) ("\\_<\\(?:from\\|import\\)\\_>" . py-import-from-face) ("\\_<\\(?:if\\|try\\)\\_>" . py-try-if-face) ("\\_<def[[:space:]]+\\(\\(?:[[:word:]]\\|_\\)+\\)" (1 py-def-face)) ("\\_<async def[[:space:]]+\\(\\(?:[[:word:]]\\|_\\)+\\)" (1 py-def-face)) ("\\_<\\(class\\)[[:space:]]+\\(\\(?:[[:word:]]\\|_\\)+\\)" (1 py-def-class-face) (2 py-class-name-face)) ("\\_<\\(?:\\(?:Ellipsis\\|False\\|No\\(?:ne\\|tImplemented\\)\\|True\\|__debug__\\)\\)\\_>" . py-pseudo-keyword-face) ("^[	 ]*\\(@\\(?:[[:word:]]\\|_\\)+\\(?:\\.\\(?:[[:word:]]\\|_\\)+\\)*\\)" (1 py-decorators-face)) ("\\_<\\(?:cls\\|self\\)\\_>" . py-object-reference-face) ...)
```

The weird behaviour beforehand can be attributed to the deprecated `mspyls` package. Sorry for the false alarm.  I am closing this issue. It would be nice, however, if both Python modes would be supported some time in the future :rainbow:  :)

**Comment by jdtsmith** [comment]
OK sounds good.  Not sure what that error is, perhaps M-x toggle-debug-on-error to see.   

Python-MLS does use quite a bit of python-mode functionality — prompt identification, indentation, fontification, some nav-commands, hidden output interruption, etc. But I don't see any a priori reason it couldn't "get along" with MELPA's python-mode in the buffer.  

If you want to take a closer look and propose some changes to make this possible, I'd be happy to explore.  For now I added a FAQ about python-mode.
